#include "stdafx.h"
#include "OGLUtilities.h"

const char * OGLUtilities::GLTypeEnumToCString(GLenum eType)
{
	switch (eType)
	{
	case GL_FLOAT: return "GL_FLOAT";
	case GL_FLOAT_VEC2: return "GL_FLOAT_VEC2";
	case GL_FLOAT_VEC3: return "GL_FLOAT_VEC3";
	case GL_FLOAT_VEC4: return "GL_FLOAT_VEC4";
	case GL_FLOAT_MAT2: return "GL_FLOAT_MAT2";
	case GL_FLOAT_MAT3: return "GL_FLOAT_MAT3";
	case GL_FLOAT_MAT4: return "GL_FLOAT_MAT4";
	case GL_FLOAT_MAT2x3: return "GL_FLOAT_MAT2x3";
	case GL_FLOAT_MAT2x4: return "GL_FLOAT_MAT2x4";
	case GL_FLOAT_MAT3x2: return "GL_FLOAT_MAT3x2";
	case GL_FLOAT_MAT3x4: return "GL_FLOAT_MAT3x4";
	case GL_FLOAT_MAT4x2: return "GL_FLOAT_MAT4x2";
	case GL_FLOAT_MAT4x3: return "GL_FLOAT_MAT4x3";
	case GL_INT: return "GL_INT";
	case GL_INT_VEC2: return "GL_INT_VEC2";
	case GL_INT_VEC3: return "GL_INT_VEC3";
	case GL_INT_VEC4: return "GL_INT_VEC4";
	case GL_UNSIGNED_INT: return "GL_UNSIGNED_INT";
	case GL_UNSIGNED_INT_VEC2: return "GL_UNSIGNED_INT_VEC2";
	case GL_UNSIGNED_INT_VEC3: return "GL_UNSIGNED_INT_VEC3";
	case GL_UNSIGNED_INT_VEC4: return "GL_UNSIGNED_INT_VEC4";
	case GL_DOUBLE: return "GL_DOUBLE";
	case GL_DOUBLE_VEC2: return "GL_DOUBLE_VEC2";
	case GL_DOUBLE_VEC3: return "GL_DOUBLE_VEC3";
	case GL_DOUBLE_VEC4: return "GL_DOUBLE_VEC4";
	case GL_DOUBLE_MAT2: return "GL_DOUBLE_MAT2";
	case GL_DOUBLE_MAT3: return "GL_DOUBLE_MAT3";
	case GL_DOUBLE_MAT4: return "GL_DOUBLE_MAT4";
	case GL_DOUBLE_MAT2x3: return "GL_DOUBLE_MAT2x3";
	case GL_DOUBLE_MAT2x4: return "GL_DOUBLE_MAT2x4";
	case GL_DOUBLE_MAT3x2: return "GL_DOUBLE_MAT3x2";
	case GL_DOUBLE_MAT3x4: return "GL_DOUBLE_MAT3x4";
	case GL_DOUBLE_MAT4x2: return "GL_DOUBLE_MAT4x2";
	case GL_DOUBLE_MAT4x3: return "GL_DOUBLE_MAT4x3";

	case GL_SAMPLER_1D: return "GL_SAMPLER_1D";
	case GL_SAMPLER_2D:	return "GL_SAMPLER_2D";
	case GL_SAMPLER_3D:	return "GL_SAMPLER_3D";
	case GL_SAMPLER_CUBE:	return "GL_SAMPLER_CUBE";
	case GL_SAMPLER_1D_SHADOW:	return "GL_SAMPLER_1D_SHADOW";
	case GL_SAMPLER_2D_SHADOW:	return "GL_SAMPLER_2D_SHADOW";
	case GL_SAMPLER_1D_ARRAY:	return "GL_SAMPLER_1D_ARRAY";
	case GL_SAMPLER_2D_ARRAY:	return "GL_SAMPLER_2D_ARRAY";
	case GL_SAMPLER_1D_ARRAY_SHADOW:	return "GL_SAMPLER_1D_ARRAY_SHADOW";
	case GL_SAMPLER_2D_ARRAY_SHADOW:	return "GL_SAMPLER_2D_ARRAY_SHADOW";
	case GL_SAMPLER_2D_MULTISAMPLE:	return "GL_SAMPLER_2D_MULTISAMPLE";
	case GL_SAMPLER_2D_MULTISAMPLE_ARRAY:	return "GL_SAMPLER_2D_MULTISAMPLE_ARRAY";
	case GL_SAMPLER_CUBE_SHADOW:return "GL_SAMPLER_CUBE_SHADOW";
	case GL_SAMPLER_BUFFER: return "GL_SAMPLER_BUFFER";
	case GL_SAMPLER_2D_RECT:	return "GL_SAMPLER_2D_RECT";
	case GL_SAMPLER_2D_RECT_SHADOW:	return "GL_SAMPLER_2D_RECT_SHADOW";
	case GL_INT_SAMPLER_1D:	return "GL_INT_SAMPLER_1D";
	case GL_INT_SAMPLER_2D:	return "GL_INT_SAMPLER_2D";
	case GL_INT_SAMPLER_3D:	return "GL_INT_SAMPLER_3D";
	case GL_INT_SAMPLER_CUBE:	return "GL_INT_SAMPLER_CUBE";
	case GL_INT_SAMPLER_1D_ARRAY:	return "GL_INT_SAMPLER_1D_ARRAY";
	case GL_INT_SAMPLER_2D_ARRAY:	return "GL_INT_SAMPLER_2D_ARRAY";
	case GL_INT_SAMPLER_2D_MULTISAMPLE:	return "GL_INT_SAMPLER_2D_MULTISAMPLE";
	case GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY:	return "GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY";
	case GL_INT_SAMPLER_BUFFER:	return "GL_INT_SAMPLER_BUFFER";
	case GL_INT_SAMPLER_2D_RECT:	return "GL_INT_SAMPLER_2D_RECT";
	case GL_UNSIGNED_INT_SAMPLER_1D:	return "GL_UNSIGNED_INT_SAMPLER_1D";
	case GL_UNSIGNED_INT_SAMPLER_2D:	return "GL_UNSIGNED_INT_SAMPLER_2D";
	case GL_UNSIGNED_INT_SAMPLER_3D:	return "GL_UNSIGNED_INT_SAMPLER_3D";
	case GL_UNSIGNED_INT_SAMPLER_CUBE:	return "GL_UNSIGNED_INT_SAMPLER_CUBE";
	case GL_UNSIGNED_INT_SAMPLER_1D_ARRAY:	return "GL_UNSIGNED_INT_SAMPLER_1D_ARRAY";
	case GL_UNSIGNED_INT_SAMPLER_2D_ARRAY:	return "GL_UNSIGNED_INT_SAMPLER_2D_ARRAY";
	case GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE:	return "GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE";
	case GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY:	return "GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY";
	case GL_UNSIGNED_INT_SAMPLER_BUFFER:	return "GL_UNSIGNED_INT_SAMPLER_BUFFER";
	case GL_UNSIGNED_INT_SAMPLER_2D_RECT:	return "GL_UNSIGNED_INT_SAMPLER_2D_RECT";
	case GL_IMAGE_1D:	return "GL_IMAGE_1D";
	case GL_IMAGE_2D:	return "GL_IMAGE_2D";
	case GL_IMAGE_3D:	return "GL_IMAGE_3D";
	case GL_IMAGE_2D_RECT:	return "GL_IMAGE_2D_RECT";
	case GL_IMAGE_CUBE:	return "GL_IMAGE_CUBE";
	case GL_IMAGE_BUFFER:	return "GL_IMAGE_BUFFER";
	case GL_IMAGE_1D_ARRAY:	return "GL_IMAGE_1D_ARRAY";
	case GL_IMAGE_2D_ARRAY: return "GL_IMAGE_2D_ARRAY";
	case GL_IMAGE_2D_MULTISAMPLE:	return "GL_IMAGE_2D_MULTISAMPLE";
	case GL_IMAGE_2D_MULTISAMPLE_ARRAY:	return "GL_IMAGE_2D_MULTISAMPLE_ARRAY";
	case GL_INT_IMAGE_1D:	return "GL_INT_IMAGE_1D";
	case GL_INT_IMAGE_2D:	return "GL_INT_IMAGE_2D";
	case GL_INT_IMAGE_3D:	return "GL_INT_IMAGE_3D";
	case GL_INT_IMAGE_2D_RECT:	return "GL_INT_IMAGE_2D_RECT";
	case GL_INT_IMAGE_CUBE:	return "GL_INT_IMAGE_CUBE";
	case GL_INT_IMAGE_BUFFER:	return "GL_INT_IMAGE_BUFFER";
	case GL_INT_IMAGE_1D_ARRAY:	return "GL_INT_IMAGE_1D_ARRAY";
	case GL_INT_IMAGE_2D_ARRAY:	return "GL_INT_IMAGE_2D_ARRAY";
	case GL_INT_IMAGE_2D_MULTISAMPLE:	return "GL_INT_IMAGE_2D_MULTISAMPLE";
	case GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY:	return "GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY";
	case GL_UNSIGNED_INT_IMAGE_1D:	return "GL_UNSIGNED_INT_IMAGE_1D";
	case GL_UNSIGNED_INT_IMAGE_2D:	return "GL_UNSIGNED_INT_IMAGE_2D";
	case GL_UNSIGNED_INT_IMAGE_3D:	return "GL_UNSIGNED_INT_IMAGE_3D";
	case GL_UNSIGNED_INT_IMAGE_2D_RECT: return "GL_UNSIGNED_INT_IMAGE_2D_RECT";
	case GL_UNSIGNED_INT_IMAGE_CUBE:	return "GL_UNSIGNED_INT_IMAGE_CUBE";
	case GL_UNSIGNED_INT_IMAGE_BUFFER:	return "GL_UNSIGNED_INT_IMAGE_BUFFER";
	case GL_UNSIGNED_INT_IMAGE_1D_ARRAY:	return "GL_UNSIGNED_INT_IMAGE_1D_ARRAY";
	case GL_UNSIGNED_INT_IMAGE_2D_ARRAY:	return "GL_UNSIGNED_INT_IMAGE_2D_ARRAY";
	case GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE:	return "GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE";
	case GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY:	return "GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY";
	case GL_UNSIGNED_INT_ATOMIC_COUNTER: return "GL_UNSIGNED_INT_ATOMIC_COUNTER";
	default:
		return "Unknown type";
	}
}

const char * OGLUtilities::GLDebugEnumToCString(GLenum eType)
{
	switch (eType)
	{

	case GL_DEBUG_SOURCE_API: return "GL_DEBUG_SOURCE_API";
	case GL_DEBUG_SOURCE_WINDOW_SYSTEM: return "GL_DEBUG_SOURCE_WINDOW_SYSTEM";
	case GL_DEBUG_SOURCE_SHADER_COMPILER: return "GL_DEBUG_SOURCE_SHADER_COMPILER";
	case GL_DEBUG_SOURCE_THIRD_PARTY: return "GL_DEBUG_SOURCE_THIRD_PARTY";
	case GL_DEBUG_SOURCE_APPLICATION: return "GL_DEBUG_SOURCE_APPLICATION";
	case GL_DEBUG_SOURCE_OTHER: return "GL_DEBUG_SOURCE_OTHER";

	case GL_DEBUG_TYPE_ERROR: return "GL_DEBUG_TYPE_ERROR";
	case GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR: return "GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR";
	case GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR: return "GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR";
	case GL_DEBUG_TYPE_PORTABILITY: return "GL_DEBUG_TYPE_PORTABILITY";
	case GL_DEBUG_TYPE_PERFORMANCE: return "GL_DEBUG_TYPE_PERFORMANCE";
	case GL_DEBUG_TYPE_MARKER: return "GL_DEBUG_TYPE_MARKER";
	case GL_DEBUG_TYPE_PUSH_GROUP: return "GL_DEBUG_TYPE_PUSH_GROUP";
	case GL_DEBUG_TYPE_POP_GROUP: return "GL_DEBUG_TYPE_POP_GROUP";
	case GL_DEBUG_TYPE_OTHER: return "GL_DEBUG_TYPE_OTHER";

	case GL_DEBUG_SEVERITY_HIGH: return "GL_DEBUG_SEVERITY_HIGH";
	case GL_DEBUG_SEVERITY_MEDIUM: return "GL_DEBUG_SEVERITY_MEDIUM";
	case GL_DEBUG_SEVERITY_LOW: return "GL_DEBUG_SEVERITY_LOW";
	case GL_DEBUG_SEVERITY_NOTIFICATION: return "GL_DEBUG_SEVERITY_NOTIFICATION";

	default:
		return "Unknown debug enum entry";
	}
}

GLenum OGLUtilities::GetErrors()
{
	GLenum error = glGetError();
	do
	{		
		switch (error)
		{
		case GL_NO_ERROR:
			std::cout << "GL_NO_ERROR" << std::endl;
			break;
		case GL_INVALID_ENUM:
			std::cout << "GL_INVALID_ENUM" << std::endl;
			break;
		case GL_INVALID_VALUE:
			std::cout << "GL_INVALID_VALUE" << std::endl;
			break;
		case GL_INVALID_OPERATION:
			std::cout << "GL_INVALID_OPERATION" << std::endl;
			break;
		case GL_INVALID_FRAMEBUFFER_OPERATION:
			std::cout << "GL_INVALID_FRAMEBUFFER_OPERATION" << std::endl;
			break;
		case GL_OUT_OF_MEMORY:
			std::cout << "GL_OUT_OF_MEMORY" << std::endl;
			break;
		case GL_STACK_UNDERFLOW:
			std::cout << "GL_STACK_UNDERFLOW" << std::endl;
			break;
		case GL_STACK_OVERFLOW:
			std::cout << "GL_STACK_OVERFLOW" << std::endl;
			break;
		default:
			std::cout << "Unknown error" << std::endl;
			break;
		}
	} while (error = glGetError() != GL_NO_ERROR);

	return error;
}

void APIENTRY OGLUtilities::DebugCallback(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar * message, const GLvoid * userParam)
{
	//printf("Debug message with source=0x%04X type=0x%04X, id %u, severity 0x%0X, '%s'\n" , source, type, id, severity, message);
	std::cout << "Debug message:\n"
			<< "\tSource: " << OGLUtilities::GLDebugEnumToCString(source) << "\n"
			<< "\tType: " << OGLUtilities::GLDebugEnumToCString(type) << "\n"
			<< "\tSeverity: " << OGLUtilities::GLDebugEnumToCString(severity) << "\n"
			<< "\tMessage: " << message << std::endl;
}
